### PR TITLE
Feat/front chat

### PR DESCRIPTION
**Pull request by Ulysseclem**
overflow fix
new button for sending game
new front for private game search
new front for flappy game search

### CODE REVIEW

**Review by cdurdetrouver — CHANGES_REQUESTED** [review]
Change boutton for send message and pong invitation

**Review by cdurdetrouver — DISMISSED** [review]
when to much message it doesn't stay in the message box

**Review by Ulysseclem — COMMENTED** [review]
test

**Review by Pypypierre — APPROVED** [review]
let's go

**Pull request merged**
